/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 ../public/models/eth-model.glb 
*/

import React from 'react'
import { useGLTF, PerspectiveCamera, OrthographicCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/eth-model.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0.139]}>
        <mesh geometry={nodes.Text012.geometry} material={materials['Color - Yellow']} />
        <mesh geometry={nodes.Text012_1.geometry} material={materials['Clay White']} />
      </group>
      <OrthographicCamera makeDefault={false} far={1000} near={0.1} position={[30.609, 30.609, 30.609]} rotation={[-0.785, 0.615, 0.524]} />
      <pointLight intensity={15} decay={2} position={[2.459, -0.915, -1.617]} rotation={[-Math.PI / 2, 0, 0]} />
      <PerspectiveCamera makeDefault={true} far={1000} near={0.1} fov={23.47} position={[0, 0, 9.73]} />
      <pointLight intensity={15} decay={2} position={[1.46, -0.963, -0.039]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={25} decay={2} position={[0.597, -2.243, 0.881]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/eth-model.glb')
